[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
<<<<<<< HEAD

# Ankr RPC endpoints (https://www.ankr.com/rpc/)
[rpc_endpoints]
eth = "${ETH_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/mI-8iQEK1K8m_VsMscNTMVx4EBtuDVmK"
base = "https://base-mainnet.g.alchemy.com/v2/mI-8iQEK1K8m_VsMscNTMVx4EBtuDVmK"
mainnet = "https://eth.llamarpc.com"
=======
via_ir = true
optimizer = true
optimizer_runs = 200
>>>>>>> 6e35dbcdcbe87ff20e97db4d278351f699abb9f6
